# Generated by Django 4.1.1 on 2022-10-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('cnic', models.IntegerField(max_length=11)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskapp.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taskapp.role')),
            ],
        ),
    ]
